### ISSUE TITLE
UI flickering and scroll is broker 

### ISSUE THREAD

**Issue by TheNaman047** [ivanfioravanti/chatbot-ollama#48]
Issues:

1. Word streaming is not working anymore, and all the response is shown at once at the end
2. UI keeps flickering till the response is streamed
3. Post response is received on the screen and rendered, the scroll is not smooth and jumps from one position to another.

Recording:

https://github.com/ivanfioravanti/chatbot-ollama/assets/25585634/7c27e6df-37ec-4e57-b065-b4d47d2b6e02

System:
![image](https://github.com/ivanfioravanti/chatbot-ollama/assets/25585634/db838c7a-ac5b-481c-86a1-6fd60fa5f6d1)

Running via docker, node 20

**Comment by RogerWeihrauch** [comment]
Hi all
Same here:
Points 1-3: same UI experience when setting up ollama with pinokio app on macOS.
- Running it under: http://localhost:3000
- Composing a prompt
- Hitting Enter to generate response
- Trying to scroll response: needs a kind of a burst 'til it starts scrolling
- screen flickers while scrolling
- and sidebar is stuck when scrolled down; gets only restarted with the before mentioned 'burst'
What infos are needed for analysation?

Regards,
Roger

**Comment by racerxdl** [comment]
Same here, on ubuntu and chrome.

**Comment by Andrew0002** [comment]
Same on macOS on Edge and Safari

**Comment by Andrew0002** [comment]
I tried going back to some older docker images and it seems like the docker image that was built on Jan 29th doesn't have this issue, but the ones after it do. I'm wondering if the problem is related to pull #36.

- Works - Jan 29
- - 	docker pull [ghcr.io/ivanfioravanti/chatbot-ollama@sha256:d79f280c842aa1629cc07627fc19d1bce3e327b45f2ba124cdbe111482f08978](http://ghcr.io/ivanfioravanti/chatbot-ollama@sha256:d79f280c842aa1629cc07627fc19d1bce3e327b45f2ba124cdbe111482f08978)
- - 	https://github.com/ivanfioravanti/chatbot-ollama/pkgs/container/chatbot-ollama/172410577

- Issue Starts - Feb 22
- - 	docker pull [ghcr.io/ivanfioravanti/chatbot-ollama@sha256:c1390ae80f0800ff28b4ff036ea5c490eccfe6ea8910655c2ec992c35f09b3a0](http://ghcr.io/ivanfioravanti/chatbot-ollama@sha256:c1390ae80f0800ff28b4ff036ea5c490eccfe6ea8910655c2ec992c35f09b3a0)
- - 	https://github.com/ivanfioravanti/chatbot-ollama/pkgs/container/chatbot-ollama/182490314

**Comment by caiyesd** [comment]
Same here, on ubuntu and chrome.

**Comment by ivanfioravanti** [comment]
> I tried going back to some older docker images and it seems like the docker image that was built on Jan 29th doesn't have this issue, but the ones after it do. I'm wondering if the problem is related to pull #36.
> 
> * Works - Jan 29
> * * ```
>     docker pull ghcr.io/ivanfioravanti/chatbot-ollama@sha256:d79f280c842aa1629cc07627fc19d1bce3e327b45f2ba124cdbe111482f08978
>     ```
> * * ```
>     https://github.com/ivanfioravanti/chatbot-ollama/pkgs/container/chatbot-ollama/172410577
>     ```
> * Issue Starts - Feb 22
> * * ```
>     docker pull ghcr.io/ivanfioravanti/chatbot-ollama@sha256:c1390ae80f0800ff28b4ff036ea5c490eccfe6ea8910655c2ec992c35f09b3a0
>     ```
> * * ```
>     https://github.com/ivanfioravanti/chatbot-ollama/pkgs/container/chatbot-ollama/182490314
>     ```

Thanks @Andrew0002 this helps!

**Comment by ivanfioravanti** [comment]
Fixed reverting recent commits. Thanks everyone!
